### ISSUE TITLE
SKIP_JOB parameters

### ISSUE THREAD

**Issue by TheSharpieOne** [circletron/circletron#6]
If a package workflow triggers a job that is defined in the package's `circle.yml` with parameters and that job is skipped it will fail since the workflow is calling `SKIP_JOB` with parameters that `SKIP_JOB` doesn't accept.

Proposed: Instead of outright replacing the job with `SKIP_JOB`, add the job's parameters into `SKIP_JOB`
https://github.com/circletron/circletron/blob/f6a67ce915d37cbf364ecca13269c2d8482fa814/src/index.ts#L205
```js
jobsConfig[jobName] = triggerPackages.has(pkg.name) ? jobData : { ...SKIP_JOB, parameters: jobData.parameters }
```

Current workaround: duplicate the job with the parameter hard-coded.

**Comment by insidewhy** [comment]
@TheSharpieOne Cool, looks like an easy fix. Wanna open a PR?
