### ISSUE TITLE
.circleci folder

### ISSUE THREAD

**Issue by jsakas** [circletron/circletron#9]
Hi, I noticed when using this package that the circletron config is required to go in a folder `.circle`.

The other configuration for Circle as outlined in their docs goes in `.circleci`: https://circleci.com/docs/2.0/configuration-reference/

So now we have two folders in our repo, `.circle` (for circletron) and `.circleci` (for everything else).

It's not an urgent issue but would be nice to keep it consistent. Our first implementation put the config file in the wrong folder because it's easy to miss.

**Comment by insidewhy** [comment]
Ah yes I should have chosen `.circleci` from the beginning. I'll update it to also load from this location and use `.circle` as a fallback for those already using configurations.

I would have noticed earlier but in all my projects I'm using the default configuration so don't need a configuration file.

**Comment by sethmcleod** [comment]
I think there may have been some confusion here. The source files are looking for `.circleci/circletron.yml` but the readme says to put that config in `.circle/circletron.yml`. I'll open a PR to update the readme so it matches what the source code expects. 

https://github.com/circletron/circletron/blob/main/src/index.ts#L223

**Comment by insidewhy** [comment]
@sethmcleod Thanks for the PR :)
